name: CI

on: [push, pull_request]

jobs:
  golang:
    name: Build and test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.20' ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - run: go version
    - run: go build ./...
    - run: go test -race ./...

    - uses: golangci/golangci-lint-action@v3
      with:
        skip-pkg-cache: true
        skip-build-cache: true
